// Cloudflare Worker entrypoint. STATIC_ASSETS is generated by scripts/build-worker.mjs.
const hitTimes = new Map();
const ROLE_NAMES = { tank: 'Tank', heal: 'Healer', melee: 'Melee DPS', ranged: 'Ranged DPS' };
const MIME = { html: 'text/html; charset=utf-8', js: 'text/javascript; charset=utf-8', css: 'text/css; charset=utf-8', json: 'application/json; charset=utf-8', svg: 'image/svg+xml', webp: 'image/webp' };

function json(data, status = 200, origin = '') {
  return new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...(origin === 'https://fantomkiller.github.io' ? { 'Access-Control-Allow-Origin': origin, Vary: 'Origin' } : {}) } });
}

function clean(value, max) {
  if (typeof value !== 'string') return '';
  return value.trim().replace(/[\u0000-\u001f\u007f]/g, ' ').slice(0, max);
}

async function apply(request, env) {
  const expectedOrigin = new URL(request.url).origin;
  const origin = request.headers.get('Origin');
  if (origin !== expectedOrigin && origin !== 'https://fantomkiller.github.io') return json({ error: 'Zgłoszenie musi pochodzić z formularza gildii.' }, 403);
  if (!request.headers.get('Content-Type')?.toLowerCase().startsWith('application/json')) return json({ error: 'Nieprawidłowy format zgłoszenia.' }, 415, origin);
  if (Number(request.headers.get('Content-Length') || 0) > 8000) return json({ error: 'Zgłoszenie jest zbyt długie.' }, 413, origin);
  const raw = await request.text();
  if (raw.length > 8000) return json({ error: 'Zgłoszenie jest zbyt długie.' }, 413, origin);
  let input;
  try { input = JSON.parse(raw); } catch { return json({ error: 'Nieprawidłowe zgłoszenie.' }, 400, origin); }
  if (!input || typeof input !== 'object' || Array.isArray(input)) return json({ error: 'Nieprawidłowe zgłoszenie.' }, 400, origin);
  if (input.website) return json({ ok: true }, 200, origin); // Hidden honeypot field.

  const data = {
    roles: Array.isArray(input.roles) ? [...new Set(input.roles)].filter((role) => typeof role === 'string' && ROLE_NAMES[role]).slice(0, 4) : [],
    className: clean(input.className, 40), specialization: clean(input.specialization, 40),
    character: clean(input.character, 32), realm: clean(input.realm, 50), discord: clean(input.discord, 60),
    logs: clean(input.logs, 300), raiderio: clean(input.raiderio, 300), experience: clean(input.experience, 80), note: clean(input.note, 1500),
    wednesday: input.wednesday === true, thursday: input.thursday === true, monday: input.monday === true,
  };
  if (!data.roles.length || !data.className || !data.specialization || !data.character || !data.realm || (!data.wednesday && !data.thursday && !data.monday)) return json({ error: 'Uzupełnij wymagane pola.' }, 400, origin);
  if (data.logs && !/^https:\/\/(www\.)?warcraftlogs\.com\//i.test(data.logs)) return json({ error: 'Podaj poprawny link do Warcraft Logs.' }, 400, origin);
  if (data.raiderio && !/^https:\/\/(www\.)?raider\.io\//i.test(data.raiderio)) return json({ error: 'Podaj poprawny link do Raider.IO.' }, 400, origin);

  const ip = request.headers.get('CF-Connecting-IP');
  const now = Date.now();
  if (hitTimes.size > 1000) hitTimes.clear();
  const last = ip ? hitTimes.get(ip) || 0 : 0;
  if (ip && now - last < 30000) return json({ error: 'Odczekaj chwilę przed kolejnym zgłoszeniem.' }, 429, origin);
  if (!env.DISCORD_APPLICATION_WEBHOOK) return json({ error: 'Rekrutacja jest chwilowo niedostępna. Odezwij się na Discordzie.' }, 503, origin);
  if (ip) hitTimes.set(ip, now);

  const fields = [
    ['Postać / realm', `${data.character} — ${data.realm} (EU)`],
    ['Role / główna klasa / spec', `${data.roles.map((role) => ROLE_NAMES[role]).join(', ')} · ${data.className} · ${data.specialization}`],
    ['Discord', data.discord || 'Nie podano'],
    ['Logi', data.logs || 'Nie podano'],
    ['Raider.IO', data.raiderio || 'Nie podano'],
    ['Doświadczenie', data.experience || 'Nie podano'],
    ['Dostępność', `Środa: ${data.wednesday ? 'tak' : 'nie'} · Czwartek: ${data.thursday ? 'tak' : 'nie'} · Dodatkowy poniedziałek: ${data.monday ? 'tak' : 'nie'}`],
    ['O sobie', data.note.slice(0, 900) || 'Nie podano'],
    ...(data.note.length > 900 ? [['O sobie — ciąg dalszy', data.note.slice(900)]] : []),
  ].map(([name, value]) => ({ name, value, inline: false }));

  try {
    const response = await fetch(env.DISCORD_APPLICATION_WEBHOOK, {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'Critical Error · Rekrutacja', allowed_mentions: { parse: [] }, embeds: [{ title: 'Nowe zgłoszenie do gildii', color: 10038582, fields, timestamp: new Date().toISOString() }] }),
    });
    if (!response.ok) { if (ip) hitTimes.delete(ip); return json({ error: 'Nie udało się dostarczyć zgłoszenia. Spróbuj ponownie lub odezwij się na Discordzie.' }, 503, origin); }
    return json({ ok: true }, 200, origin);
  } catch (_) {
    if (ip) hitTimes.delete(ip);
    return json({ error: 'Nie udało się dostarczyć zgłoszenia. Spróbuj ponownie lub odezwij się na Discordzie.' }, 503, origin);
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === '/api/apply') {
      if (request.method === 'OPTIONS' && request.headers.get('Origin') === 'https://fantomkiller.github.io') return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': 'https://fantomkiller.github.io', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Max-Age': '86400', Vary: 'Origin' } });
      if (request.method !== 'POST') return json({ error: 'Metoda niedozwolona.' }, 405);
      return apply(request, env);
    }
    if (request.method !== 'GET' && request.method !== 'HEAD') return new Response('Method not allowed', { status: 405 });
    const path = url.pathname === '/' ? '/index.html' : url.pathname;
    if (!Object.hasOwn(STATIC_ASSETS, path)) return new Response('Not found', { status: 404 });
    const extension = path.split('.').pop();
    const bytes = Uint8Array.from(atob(STATIC_ASSETS[path]), (character) => character.charCodeAt(0));
    const cache = path.includes('/assets/index-') ? 'public, max-age=31536000, immutable' : 'no-store';
    return new Response(request.method === 'HEAD' ? null : bytes, { headers: { 'Content-Type': MIME[extension] || 'application/octet-stream', 'Cache-Control': cache, 'X-Content-Type-Options': 'nosniff' } });
  },
};
