// Cloudflare Worker entrypoint. STATIC_ASSETS is generated by scripts/build-worker.mjs.
const hitTimes = new Map();
const ROLE_NAMES = { tank: 'Tank', heal: 'Healer', melee: 'Melee DPS', ranged: 'Ranged DPS' };
const MIME = { html: 'text/html; charset=utf-8', js: 'text/javascript; charset=utf-8', css: 'text/css; charset=utf-8', json: 'application/json; charset=utf-8', svg: 'image/svg+xml', webp: 'image/webp', jpg: 'image/jpeg', jpeg: 'image/jpeg' };
const rosterCache = {};
const mplusCache = {};
const ROSTER_TTL = 5 * 60 * 1000;
const MPLUS_TTL = 15 * 60 * 1000;
const CURRENT_MPLUS_LEVEL = 90;

function json(data, status = 200, origin = '') {
  return new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...(origin === 'https://fantomkiller.github.io' ? { 'Access-Control-Allow-Origin': origin, Vary: 'Origin' } : {}) } });
}

function clean(value, max) {
  if (typeof value !== 'string') return '';
  return value.trim().replace(/[\u0000-\u001f\u007f]/g, ' ').slice(0, max);
}

async function loadRoster(env) {
  let players = env.ROSTER_FALLBACK || BUILT_ROSTER;
  if (env.WOWAUDIT_API_KEY) {
    const response = await fetch('https://api.wowaudit.com/v1/characters', {
      headers: { Authorization: `Bearer ${env.WOWAUDIT_API_KEY}` },
      signal: AbortSignal.timeout(10000),
    });
    if (!response.ok) throw new Error(`WoWAudit HTTP ${response.status}`);
    const roster = await response.json();
    if (!Array.isArray(roster)) throw new Error('WoWAudit returned an invalid roster');
    players = roster.filter((character) => character && character.rank?.toLowerCase() === 'main' && character.status?.toLowerCase() !== 'archived')
      .map((character) => ({
        name: character.name, realm: character.realm, className: character.class,
        role: character.role?.toLowerCase(),
      })).filter((character) => typeof character.name === 'string' && typeof character.realm === 'string' && typeof character.className === 'string' && ['tank', 'heal', 'melee', 'ranged'].includes(character.role));
    if (!players.length) throw new Error('WoWAudit returned no main characters');
  }

  const enriched = new Array(players.length);
  let cursor = 0;
  async function addStats() {
    while (cursor < players.length) {
      const index = cursor++;
      const player = players[index];
      const profile = new URL('https://raider.io/api/v1/characters/profile');
      profile.search = new URLSearchParams({ region: 'eu', realm: player.realm, name: player.name, fields: 'gear,mythic_plus_scores_by_season:current' });
      let itemLevel = null;
      let score = null;
      try {
        const response = await fetch(profile, { signal: AbortSignal.timeout(6500) });
        if (!response.ok) throw new Error(`Raider.IO HTTP ${response.status}`);
        const data = await response.json();
        const gear = Number(data.gear?.item_level_equipped);
        const rating = Number(data.mythic_plus_scores_by_season?.[0]?.scores?.all);
        if (Number.isFinite(gear) && gear > 0) itemLevel = Math.round(gear);
        if (Number.isFinite(rating) && rating >= 0 && data.mythic_plus_scores_by_season?.length) score = Math.round(rating);
      } catch (error) {
        console.warn(`No current profile for ${player.name}: ${String(error)}`);
      }
      enriched[index] = { name: player.name, className: player.className, role: player.role, realm: player.realm, itemLevel, score };
    }
  }
  await Promise.all(Array.from({ length: Math.min(8, players.length) }, () => addStats()));
  return { players: enriched, updatedAt: new Date().toISOString() };
}

async function getRoster(request, env) {
  const origin = request.headers.get('Origin') || '';
  const cache = env.ROSTER_CACHE || rosterCache;
  if (cache.payload && cache.until > Date.now()) return json(cache.payload, 200, origin);
  const edgeCache = typeof caches !== 'undefined' && caches.default && !env.ROSTER_CACHE ? caches.default : null;
  const cacheRequest = new Request(new URL('/__roster_cache', request.url));
  if (edgeCache) {
    const saved = await edgeCache.match(cacheRequest);
    if (saved) {
      cache.payload = await saved.json();
      cache.until = Date.now() + ROSTER_TTL;
      return json(cache.payload, 200, origin);
    }
  }
  if (!cache.pending) cache.pending = loadRoster(env).then(async (payload) => {
    cache.payload = payload;
    cache.until = Date.now() + ROSTER_TTL;
    if (edgeCache) await edgeCache.put(cacheRequest, new Response(JSON.stringify(payload), { headers: { 'Content-Type': 'application/json', 'Cache-Control': 'public, max-age=300' } }));
    return payload;
  }).finally(() => { cache.pending = null; });
  try { return json(await cache.pending, 200, origin); }
  catch (error) { console.warn(`Roster refresh failed: ${String(error)}`); return json({ error: 'Skład jest chwilowo niedostępny.' }, 503, origin); }
}

async function getMplus(request, env) {
  const origin = request.headers.get('Origin') || '';
  const cache = env.MPLUS_CACHE || mplusCache;
  const rawPage = new URL(request.url).searchParams.get('page') || '0';
  if (!/^(0|[1-9]\d{0,2})$/.test(rawPage)) return json({ error: 'Nieprawidłowa strona rankingu.' }, 400, origin);
  const page = Number(rawPage);
  if (!cache.characters || cache.rosterUntil <= Date.now()) {
    if (!cache.rosterPending) cache.rosterPending = (async () => {
    const guildUrl = new URL('https://raider.io/api/v1/guilds/profile');
    guildUrl.search = new URLSearchParams({ region: 'eu', realm: 'burning-legion', name: 'Critical Error', fields: 'members' });
    const response = await fetch(guildUrl, { signal: AbortSignal.timeout(10000) });
    if (!response.ok) throw new Error(`Raider.IO guild HTTP ${response.status}`);
    const guild = await response.json();
    if (!Array.isArray(guild.members)) throw new Error('Raider.IO returned an invalid guild roster');
    let players = guild.members.filter((member) => Number(member.character?.level) === CURRENT_MPLUS_LEVEL).map((member) => ({
      name: member.character?.name, realm: member.character?.realm, className: member.character?.class,
    })).filter((character) => typeof character.name === 'string' && typeof character.realm === 'string' && typeof character.className === 'string');
    const seen = new Set();
    players = players.filter((player) => {
      const key = `${player.name.toLowerCase()}@${player.realm.toLowerCase()}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    if (!players.length) throw new Error('Raider.IO returned no max-level guild members');
    return players;
    })().then((players) => {
      cache.characters = players;
      cache.scope = 'guild';
      cache.pages = {};
      cache.rosterUntil = Date.now() + MPLUS_TTL;
    }).finally(() => { cache.rosterPending = null; });
    try { await cache.rosterPending; }
    catch (error) { console.warn(`M+ roster refresh failed: ${String(error)}`); return json({ error: 'Ranking M+ jest chwilowo niedostępny.' }, 503, origin); }
  }
  if (page * 40 >= cache.characters.length && page > 0) return json({ error: 'Nieprawidłowa strona rankingu.' }, 400, origin);
  const saved = cache.pages[page];
  if (saved?.payload) return json(saved.payload, 200, origin);
  if (!saved?.pending) {
    const pageCache = (cache.pages[page] = {});
    pageCache.pending = (async () => {
    const players = cache.characters.slice(page * 40, (page + 1) * 40);
    const enriched = new Array(players.length);
    let cursor = 0;
    async function addStats() {
      while (cursor < players.length) {
        const index = cursor++;
        const player = players[index];
        const profile = new URL('https://raider.io/api/v1/characters/profile');
        profile.search = new URLSearchParams({ region: 'eu', realm: player.realm, name: player.name, fields: 'gear,mythic_plus_scores_by_season:current' });
        let itemLevel = null;
        let score = null;
        let profileUrl = `https://raider.io/characters/eu/${encodeURIComponent(player.realm.toLowerCase().replace(/\s+/g, '-'))}/${encodeURIComponent(player.name)}`;
        const response = await fetch(profile, { signal: AbortSignal.timeout(6500) });
        if (response.ok) {
          const data = await response.json();
          const gear = Number(data.gear?.item_level_equipped);
          const rating = Number(data.mythic_plus_scores_by_season?.[0]?.scores?.all);
          if (Number.isFinite(gear) && gear > 0) itemLevel = Math.round(gear);
          if (Number.isFinite(rating) && rating >= 0 && data.mythic_plus_scores_by_season?.length) score = Math.round(rating);
          if (typeof data.profile_url === 'string' && /^https:\/\/raider\.io\/characters\//.test(data.profile_url)) profileUrl = data.profile_url;
        } else if (response.status !== 404) throw new Error(`Raider.IO HTTP ${response.status}`);
        enriched[index] = { name: player.name, realm: player.realm, className: player.className, itemLevel, score, profileUrl };
      }
    }
    await Promise.all(Array.from({ length: Math.min(6, players.length) }, () => addStats()));
    return { players: enriched, nextPage: (page + 1) * 40 < cache.characters.length ? page + 1 : null, scope: cache.scope };
    })().then((payload) => { pageCache.payload = payload; return payload; }).finally(() => { pageCache.pending = null; });
  }
  try { return json(await cache.pages[page].pending || cache.pages[page].payload, 200, origin); }
  catch (error) { console.warn(`M+ refresh failed: ${String(error)}`); return json({ error: 'Ranking M+ jest chwilowo niedostępny.' }, 503, origin); }
}

async function apply(request, env) {
  const expectedOrigin = new URL(request.url).origin;
  const origin = request.headers.get('Origin');
  if (origin !== expectedOrigin && origin !== 'https://fantomkiller.github.io') return json({ error: 'Zgłoszenie musi pochodzić z formularza gildii.' }, 403);
  if (!request.headers.get('Content-Type')?.toLowerCase().startsWith('application/json')) return json({ error: 'Nieprawidłowy format zgłoszenia.' }, 415, origin);
  if (Number(request.headers.get('Content-Length') || 0) > 8000) return json({ error: 'Zgłoszenie jest zbyt długie.' }, 413, origin);
  const raw = await request.text();
  if (raw.length > 8000) return json({ error: 'Zgłoszenie jest zbyt długie.' }, 413, origin);
  let input;
  try { input = JSON.parse(raw); } catch { return json({ error: 'Nieprawidłowe zgłoszenie.' }, 400, origin); }
  if (!input || typeof input !== 'object' || Array.isArray(input)) return json({ error: 'Nieprawidłowe zgłoszenie.' }, 400, origin);
  if (input.website) return json({ ok: true }, 200, origin); // Hidden honeypot field.

  const data = {
    roles: Array.isArray(input.roles) ? [...new Set(input.roles)].filter((role) => typeof role === 'string' && ROLE_NAMES[role]).slice(0, 4) : [],
    className: clean(input.className, 40), specialization: clean(input.specialization, 40),
    character: clean(input.character, 32), realm: clean(input.realm, 50), discord: clean(input.discord, 100),
    expectations: clean(input.expectations, 600), availability: clean(input.availability, 500),
    contactTime: clean(input.contactTime, 120),
    logs: clean(input.logs, 300), raiderio: clean(input.raiderio, 300), experience: clean(input.experience, 80), note: clean(input.note, 1500),
    wednesday: input.wednesday === true, thursday: input.thursday === true, monday: input.monday === true,
  };
  if (!data.roles.length || !data.className || !data.specialization || !data.character || !data.realm || (!data.wednesday && !data.thursday && !data.monday)) return json({ error: 'Uzupełnij wymagane pola.' }, 400, origin);
  if (!/^[a-z0-9._]{2,32}$/.test(data.discord) || data.discord.includes('..')) return json({ error: 'Podaj pełną nazwę użytkownika Discord, na przykład gracz.123. Bez @, spacji i numeru #1234.' }, 400, origin);
  if (!data.expectations || !data.availability || !data.contactTime) return json({ error: 'Uzupełnij oczekiwania, dostępność i godziny krótkiej rozmowy.' }, 400, origin);
  if (data.logs && !/^https:\/\/(www\.)?warcraftlogs\.com\//i.test(data.logs)) return json({ error: 'Podaj poprawny link do Warcraft Logs.' }, 400, origin);
  if (data.raiderio && !/^https:\/\/(www\.)?raider\.io\//i.test(data.raiderio)) return json({ error: 'Podaj poprawny link do Raider.IO.' }, 400, origin);

  const ip = request.headers.get('CF-Connecting-IP');
  const now = Date.now();
  if (hitTimes.size > 1000) hitTimes.clear();
  const last = ip ? hitTimes.get(ip) || 0 : 0;
  if (ip && now - last < 30000) return json({ error: 'Odczekaj chwilę przed kolejnym zgłoszeniem.' }, 429, origin);
  if (!env.DISCORD_APPLICATION_WEBHOOK) return json({ error: 'Rekrutacja jest chwilowo niedostępna. Odezwij się na Discordzie.' }, 503, origin);
  if (ip) hitTimes.set(ip, now);

  const fields = [
    ['Postać / realm', `${data.character} · ${data.realm} (EU)`],
    ['Role / główna klasa / spec', `${data.roles.map((role) => ROLE_NAMES[role]).join(', ')} · ${data.className} · ${data.specialization}`],
    ['Kontakt na Discordzie', data.discord],
    ['Kiedy się odezwać', data.contactTime || 'Nie podano'],
    ['Logi', data.logs || 'Nie podano'],
    ['Raider.IO', data.raiderio || 'Nie podano'],
    ['Doświadczenie', data.experience || 'Nie podano'],
    ['Wieczory raidowe', `Środa: ${data.wednesday ? 'tak' : 'nie'} · Czwartek: ${data.thursday ? 'tak' : 'nie'} · Dodatkowy poniedziałek: ${data.monday ? 'tak' : 'nie'}`],
    ['Dostępność i czas na grę', data.availability],
    ['Czego szuka w gildii', data.expectations],
    ['O sobie', data.note.slice(0, 900) || 'Nie podano'],
    ...(data.note.length > 900 ? [['O sobie (ciąg dalszy)', data.note.slice(900)]] : []),
  ].map(([name, value]) => ({ name, value, inline: false }));

  try {
    const response = await fetch(env.DISCORD_APPLICATION_WEBHOOK, {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'Critical Error · Rekrutacja', allowed_mentions: { parse: [] }, embeds: [{ title: 'Nowe zgłoszenie do gildii', color: 10038582, fields, timestamp: new Date().toISOString() }] }),
    });
    if (!response.ok) { if (ip) hitTimes.delete(ip); return json({ error: 'Nie udało się dostarczyć zgłoszenia. Spróbuj ponownie lub odezwij się na Discordzie.' }, 503, origin); }
    return json({ ok: true }, 200, origin);
  } catch (_) {
    if (ip) hitTimes.delete(ip);
    return json({ error: 'Nie udało się dostarczyć zgłoszenia. Spróbuj ponownie lub odezwij się na Discordzie.' }, 503, origin);
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === '/api/roster') {
      if (request.method !== 'GET') return json({ error: 'Metoda niedozwolona.' }, 405);
      return getRoster(request, env);
    }
    if (url.pathname === '/api/mplus') {
      if (request.method !== 'GET') return json({ error: 'Metoda niedozwolona.' }, 405);
      return getMplus(request, env);
    }
    if (url.pathname === '/api/apply') {
      if (request.method === 'OPTIONS' && request.headers.get('Origin') === 'https://fantomkiller.github.io') return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': 'https://fantomkiller.github.io', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Max-Age': '86400', Vary: 'Origin' } });
      if (request.method !== 'POST') return json({ error: 'Metoda niedozwolona.' }, 405);
      return apply(request, env);
    }
    if (request.method !== 'GET' && request.method !== 'HEAD') return new Response('Method not allowed', { status: 405 });
    const path = url.pathname === '/' ? '/index.html' : url.pathname;
    if (!Object.hasOwn(STATIC_ASSETS, path)) return new Response('Not found', { status: 404 });
    const extension = path.split('.').pop();
    const bytes = Uint8Array.from(atob(STATIC_ASSETS[path]), (character) => character.charCodeAt(0));
    const cache = path.includes('/assets/index-') ? 'public, max-age=31536000, immutable' : 'no-store';
    return new Response(request.method === 'HEAD' ? null : bytes, { headers: { 'Content-Type': MIME[extension] || 'application/octet-stream', 'Cache-Control': cache, 'X-Content-Type-Options': 'nosniff' } });
  },
};
